on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI
env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Lint (clippy)
        run: cargo clippy --all-features --all-targets
      - name: Lint (rustfmt)
        run: cargo xfmt --check
      - name: Install cargo readme
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-readme
          version: latest
      - name: Run cargo readme
        run: ./scripts/regenerate-readmes.sh
      - name: Check for differences
        run: git diff --exit-code

  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [1.56, stable]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@nextest
      # Build all targets to ensure examples are built as well.
      - name: Build
        run: cargo hack --feature-powerset build --all-targets
      - name: Test
        run: cargo hack --feature-powerset nextest run --all-targets
      - name: Run doctests
        run: cargo hack --feature-powerset test --doc
