on:
  push:
    branches:
      - main

name: Docs

jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        env:
          # So that feature(doc_cfg) can be used.
          RUSTC_BOOTSTRAP: 1
          RUSTDOCFLAGS: --cfg doc_cfg
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features
      - name: Organize
        run: |
          mkdir target/gh-pages
          touch target/gh-pages/.nojekyll
          mv target/doc target/gh-pages/rustdoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/gh-pages
